apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: upload
  template:
    metadata:
      labels:
        app: upload
    spec:
      containers:
      - name: upload
        image: my-upload-service-image:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nfs-storage
          mountPath: /data/uploads # Adjust the mountPath as needed
      volumes:
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: upload-service
spec:
  selector:
    app: upload
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
